export const connectedCities = {
  Paris: ['Essen', 'London', 'Madrid', 'Milan', 'Algiers'],
  Chicago: [
    'Atlanta',
    'San Francisco',
    'Montréal',
    'Los Angeles',
    'Mexico City'
  ],
  Madrid: ['London', 'New York', 'Paris', 'São Paulo', 'Algiers'],
  Essen: ['London', 'Milan', 'Paris', 'St. Petersburg'],
  London: ['Essen', 'Madrid', 'New York', 'Paris'],
  'New York': ['London', 'Madrid', 'Montréal', 'Washington'],
  Washington: ['Atlanta', 'New York', 'Montréal', 'Miami'],
  'San Francisco': ['Chicago', 'Manila', 'Tokyo', 'Los Angeles'],
  Montréal: ['Chicago', 'New York', 'Washington'],
  Atlanta: ['Chicago', 'Washington', 'Miami'],
  Milan: ['Essen', 'Paris', 'Istanbul'],
  'St. Petersburg': ['Essen', 'Istanbul', 'Moscow'],
  Bogotá: ['Buenos Aires', 'Lima', 'Mexico City', 'Miami', 'São Paulo'],
  'Mexico City': ['Bogotá', 'Lima', 'Los Angeles', 'Miami', 'Chicago'],
  Khartoum: ['Johannesburg', 'Kinshasa', 'Lagos', 'Cairo'],
  'São Paulo': ['Bogotá', 'Buenos Aires', 'Lagos', 'Madrid'],
  Miami: ['Bogotá', 'Mexico City', 'Atlanta', 'Washington'],
  'Los Angeles': ['Mexico City', 'Chicago', 'San Francisco', 'Sydney'],
  Kinshasa: ['Johannesburg', 'Khartoum', 'Lagos'],
  Lagos: ['Khartoum', 'Kinshasa', 'São Paulo'],
  Lima: ['Bogotá', 'Mexico City', 'Santiago'],
  'Buenos Aires': ['Bogotá', 'São Paulo'],
  Johannesburg: ['Khartoum', 'Kinshasa'],
  Santiago: ['Lima'],
  Istanbul: [
    'Algiers',
    'Baghdad',
    'Cairo',
    'Moscow',
    'Milan',
    'St. Petersburg'
  ],
  Baghdad: ['Cairo', 'Istanbul', 'Karachi', 'Riyadh', 'Tehran'],
  Delhi: ['Chennai', 'Karachi', 'Kolkata', 'Mumbai', 'Tehran'],
  Karachi: ['Baghdad', 'Delhi', 'Mumbai', 'Riyadh', 'Tehran'],
  Cairo: ['Algiers', 'Baghdad', 'Istanbul', 'Riyadh', 'Khartoum'],
  Chennai: ['Delhi', 'Kolkata', 'Mumbai', 'Bangkok', 'Jakarta'],
  Tehran: ['Baghdad', 'Delhi', 'Karachi', 'Moscow'],
  Algiers: ['Cairo', 'Istanbul', 'Madrid', 'Paris'],
  Kolkata: ['Chennai', 'Delhi', 'Bangkok', 'Hong Kong'],
  Mumbai: ['Chennai', 'Delhi', 'Karachi'],
  Riyadh: ['Baghdad', 'Cairo', 'Karachi'],
  Moscow: ['Istanbul', 'Tehran', 'St. Petersburg'],
  'Hong Kong': [
    'Bangkok',
    'Ho Chi Minh City',
    'Manila',
    'Shanghai',
    'Taipei',
    'Kolkata'
  ],
  Shanghai: ['Beijing', 'Hong Kong', 'Seoul', 'Taipei', 'Tokyo'],
  Manila: [
    'Ho Chi Minh City',
    'Hong Kong',
    'Sydney',
    'Taipei',
    'San Francisco'
  ],
  Bangkok: ['Ho Chi Minh City', 'Hong Kong', 'Jakarta', 'Chennai', 'Kolkata'],
  'Ho Chi Minh City': ['Bangkok', 'Hong Kong', 'Jakarta', 'Manila'],
  Taipei: ['Hong Kong', 'Manila', 'Osaka', 'Shanghai'],
  Jakarta: ['Bangkok', 'Ho Chi Minh City', 'Sydney', 'Chennai'],
  Tokyo: ['Osaka', 'Seoul', 'Shanghai', 'San Francisco'],
  Seoul: ['Beijing', 'Shanghai', 'Tokyo'],
  Sydney: ['Jakarta', 'Manila', 'Los Angeles'],
  Beijing: ['Seoul', 'Shanghai'],
  Osaka: ['Taipei', 'Tokyo']
}
